services:
  backend:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - logs:/app/logs
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
volumes:
  postgres_data:
  logs:
